# Farm Planning


## Problem Description

A farmer with a 200-acre farm wishes to create a five-year production plan.

Currently, he has a herd of 120 cows comprising 20 heifers (young female cows) and 100 adult dairy cows. Each heifer requires 2/3 of an acre to support it and each dairy cow requires one acre.

On average, a dairy cow produces 1.1 calves per year. Half of these calves will be bullocks that are sold shortly after birth for an average of $\$30$ each. The remaining calves, heifers, can either be sold for $\$40$ or raised until age two when they will become dairy cows. For the current year, all heifers identified for sale have already been sold.

The general practice is to sell all dairy animals at the age of 12 for an average of $\$120$ each. However, each year an average of $5\%$ of heifers and $2\%$ of dairy animals die. At present, the farmer’s herd of 120 cows is evenly distributed with 10 cows per age from newborn to 11 years old.

The milk from a dairy cow can be sold for $\$370$ annually. The farmer can currently house up to 130 cows, but this capacity limit can be increased for $\$200$ per additional cow.

Each dairy cow requires 0.6 tons of grain and 0.7 tons of sugar beet per year. Both of these can be grown on the farm. Each acre can yield 1.5 tons of sugar beet. However, only 80 acres are suitable for growing grain, and those acres have different levels of productivity as follows:

| Land Group | Area (Acres) | Grain Production (Tons/Acre) |
| --- | --- | --- |
| Group 1 | 20 | 1.10 |
| Group 2 | 30 | 0.90 |
| Group 3 | 20 | 0.80 |
| Group 4 | 10 | 0.65 |

Sugar beet can be bought for $\$70$ a ton and sold for $\$58$ a ton. Grain can be bought for $\$90$ a ton and sold for $\$75$ a ton.

The annual labor requirements for cows as well as grain and sugar beet production are as follows:

| <i></i> | Labor Required (Hr/Year) |
| --- | --- |
| Heifer | 10 |
| Milk-producing Cow | 42 |
| Acre Devoted to Grain | 4 |
| Acre Devoted to Sugar Beet| 14 |

Other annual costs are as follows:

| <i></i> | Cost (USD/Year) |
| --- | --- |
| Heifer | 50 |
| Milk-producing Cow | 100 |
| Acre Devoted to Grain | 15 |
| Acre Devoted to Sugar Beet| 10 |

Labor currently costs the farmer $\$4000$ per year and that cost provides 5,500 hours of labor. Additional labor can be paid for at the rate of $\$1.20$ per hour.

Any capital expenditure can be financed with a 10-year loan at $15\%$ interest annually. The interest and principal are paid back in 10 equal annual payments. It is prohibited for the annual cash flow to be negative.

The farmer does not want to reduce the total number of dairy cows at the end of the five-year period by more than $50\%$, nor does he want to increase their number by more than $75\%$.

What plan should the farmer follow over the next five years in order to maximize profit?

---
## Model Formulation

### Sets and Indices

$t \in \text{Years}=\{1,2,\dots,5\}$: Set of years.

$l \in \text{Lands}=\{1,2,3,4\}$: Set of land groups.

$k \in \text{Ages}=\{1,2,\dots,12\}$: Set of cow ages.

### Parameters

$\text{Installment} \in \mathbb{R}^+$: Annual payment for each $\$200$ loan. It can be computed as follows.

$$
\text{Installment}= \text{Loan}*r*\frac{(1+r)^n}{(1+r)^n-1},
$$

where $\text{Loan}$ is the loan amount of $\$200$, $r$ is the interest rate of $15\%$, and $n$ represents the ten-year period. Note that the book reports a value of $\$39.71$ instead of $\$39.85$.

$\text{Housing_cap} \in \mathbb{N}$: Number of cows that can be housed.

$\text{Land_cap} \in \mathbb{R}^+$: Land available (in Acres).

$\text{Labor_cap} \in \mathbb{R}^+$: Regular labor available (in hours) in a year.

$\text{seed1_intake} \in \mathbb{R}^+$: Tons of grain consumed by a dairy cow in a year.

$\text{seed2_intake} \in \mathbb{R}^+$: Tons of sugar beet consumed by a dairy cow in a year.

$\text{baby_animal_land} \in \mathbb{R}^+$: Acres required for sustaining each heifer.

$\text{baby_animal_labor} \in \mathbb{R}^+$: Hours of labor required in a year by each heifer.

$\text{animal_labor} \in \mathbb{R}^+$: Hours of labor required in a year by each dairy cow.

$\text{seed1_labor} \in \mathbb{R}^+$: Hours of labor required in a year by each acre of land devoted to grains.

$\text{seed2_labor} \in \mathbb{R}^+$: Hours of labor required in a year by each acre of land devoted to sugar beet.

$\text{baby_animal_decay} \in [0,1] \subset \mathbb{R}^+$: Average proportion of heifers that die in a year.

$\text{animal_decay} \in [0,1] \subset \mathbb{R}^+$: Average proportion of dairy cows that die in a year.

$\text{Birthrate} \in \mathbb{R}^+$: Expected number of calves produced by a dairy cow in a year.

$\text{min_final_animals} \in \mathbb{N}$: Minimum number of dairy cows at the end of the planning horizon.

$\text{max_final_animals} \in \mathbb{N}$: Maximum number of dairy cows at the end of the planning horizon.

$\text{initial_baby_animal_number} \in \mathbb{R}^+$: Number of heifers of each age at the beginning of the planning horizon.

$\text{initial_animals_number} \in \mathbb{R}^+$: Number of dairy cows of each age at the beginning of the planning horizon.

$\text{BL_price} \in \mathbb{R}^+$: Price for selling one bullock.

$\text{baby_animal_price} \in \mathbb{R}^+$: Price for selling one heifer.

$\text{animal_price} \in \mathbb{R}^+$: Price for selling one dairy cow.

$\text{animal_yearly_income} \in \mathbb{R}^+$: Price for selling the milk produced by a dairy cow in a year.

$\text{seed1_price} \in \mathbb{R}^+$: Price for selling a ton of grain.

$\text{seed2_price} \in \mathbb{R}^+$: Price for selling a ton of sugar beet.

$\text{seed1_cost} \in \mathbb{R}^+$: Cost for purchasing a ton of grain.

$\text{seed2_cost} \in \mathbb{R}^+$: Cost for purchasing a ton of sugar beet.

$\text{Overtime_cost} \in \mathbb{R}^+$: Cost for getting an hour of overtime.

$\text{Regular_time_cost} \in \mathbb{R}^+$: Cost for having 5,500 hours of labor in regular time.

$\text{baby_animal_cost} \in \mathbb{R}^+$: Yearly cost for supporting a heifer.

$\text{animal_cost} \in \mathbb{R}^+$: Yearly cost for supporting a dairy cow.

$\text{seed1_land_cost} \in \mathbb{R}^+$: Yearly cost for supporting an acre of land devoted to grain.

$\text{seed2_land_cost} \in \mathbb{R}^+$: Yearly cost for supporting an acre of land devoted to sugar beet.

$\text{seed2_yield} \in \mathbb{R}^+$: Sugar beet yield.

$\text{seed1_yield}_l \in \mathbb{R}^+$: Grain yield at land group $l$.

$\text{seed1_area}_l \in \mathbb{R}^+$: Number of acres suitable for growing grain in land group $l$.

### Decision Variables

$\text{Outlay}_t \in \mathbb{R}^+$: Amount of money (in units of $\$200$) spent on renting houses in year $t$.

$\text{Overtime}_t \in \mathbb{R}^+$: Number of extra labor hours needed in year $t$.

$\text{Newborn}_t \in \mathbb{R}^+$: Number of newborn heifers left in year $t$ to be raised.

$\text{HF_sell}_t \in \mathbb{R}^+$: Number of newborn heifers to sell in year $t$.

$\text{Profit}_t \in \mathbb{R}^+$: Profit attained in year $t$.

$\text{SB_buy}_t \in \mathbb{R}^+$: Number of tons of sugar beet to buy in year $t$.

$\text{SB_sell}_t \in \mathbb{R}^+$: Number of tons of sugar beet to sell in year $t$.

$\text{GR_buy}_t \in \mathbb{R}^+$: Number of tons of grain to buy in year $t$.

$\text{GR_sell}_t \in \mathbb{R}^+$: Number of tons of grain to sell in year $t$.

$\text{SB}_t \in \mathbb{R}^+$: Number of tons of sugar beet to grow in year $t$.

$\text{GR}_{t,l} \in \mathbb{R}^+$: Number of tons of grain to grow in year $t$ at land group $l$.

$\text{Cows}_{t,k} \in \mathbb{R}^+$: Number of cows of age $k$ available in year $t$.


### Objective Function

- **Profit**: Maximize the total profit (in USD) of the planning horizon. Notice that, to make capital expenditure as costly in latter years as in former ones, it is necessary to subtract pending loan payments.

\begin{equation}
\text{Maximize} \quad Z = \sum_{t \in \text{Years}}{\text{Profit}_t - installment*(t+4)*\text{Outlay}_t}
\end{equation}

### Constraints

- **Housing Capacity**: Livestock cannot exceed the installed capacity plus house rental in year $t$.

\begin{equation}
\text{Newborn}_t + \sum_{k \in \text{Ages} \setminus \{12\}}{\text{Cows}_{t,k}} \leq \text{Housing_cap} + \sum_{d \in \text{Years}: d \leq t}{\text{Outlay}_d} \quad \forall t \in \text{Years}
\end{equation}

- **Food Consumption**: There must be enough food to feed the livestock in year $t$.

- Grain.

\begin{equation}
\sum_{k \in \text{Ages} \setminus \{1,12\}}{\text{seed1_intake}*\text{Cows}_{t,k}} \leq \text{GR_buy}_t - \text{GR_sell}_t + \sum_{l \in \text{Lands}}{\text{GR}_{t,l}} \quad \forall t \in \text{Years}
\end{equation}

- Sugar beet.

\begin{equation}
\sum_{k \in \text{Ages} \setminus \{1,12\}}{\text{seed2_intake}*\text{Cows}_{t,k}} \leq \text{SB_buy}_t - \text{SB_sell}_t + \text{SB}_t \quad \forall t \in \text{Years}
\end{equation}

- **Grain Growing**: Grain produced on land $l$ cannot exceed the production capacity of year $t$.

\begin{equation}
\text{GR}_{t,l} \leq \text{seed1_yield}_l*\text{seed1_area}_l \quad \forall (t,l) \in \text{Years} \times \text{Lands}
\end{equation}

- **Land Capacity**: Use of space in year $t$ cannot exceed available land.

\begin{equation}
\frac{1}{\text{seed2_yield}}*\text{SB}_t + \text{baby_animal_land}*(\text{Newborn}_t + \text{Cow}_{t,1}) + 
\end{equation}

\begin{equation}
\sum_{k \in \text{Ages} \setminus \{1,12\}}{\text{Cows}_{t,k}} + 
\end{equation}

\begin{equation}
\sum_{l \in \text{Lands}}{\frac{\text{GR}_{t,l}}{\text{seed1_yield}_l}} \leq \text{Land_cap} \quad \forall t \in \text{Years}
\end{equation}

- **Labor**: Labor required to run the farm in year $t$ cannot exceed contracted time plus overtime.

\begin{equation}
\text{baby_animal_labor}*(\text{Newborn}_t + \text{Cow}_{t,1}) + 
\end{equation}

\begin{equation}
\sum_{k \in \text{Ages} \setminus \{1,12\}}{\text{animal_labor}*\text{Cow}_{t,k}} + 
\end{equation}

\begin{equation}
\sum_{l \in \text{Lands}}{\frac{\text{seed1_labor}*\text{GR}_{t,l}}{\text{seed1_yield}_l}} + 
\end{equation}

\begin{equation}
\frac{\text{seed2_labor}*\text{SB}_t}{\text{seed2_yield}} \leq \text{Labor_cap} + \text{Overtime}_t \qquad \forall t \in \text{Years}
\end{equation}


- **Continuity**: Livestock in year $t$ have to survive the previous year.

\begin{equation}
\text{Cows}_{t,1} = (1-\text{baby_animal_decay})*\text{Newborn}_{t-1} \quad \forall t \in \text{Years} \setminus \{1\}
\end{equation}

\begin{equation}
\text{Cows}_{t,2} = (1-\text{baby_animal_decay})*\text{Cows}_{t-1,1} \quad \forall t \in \text{Years} \setminus \{1\}
\end{equation}

\begin{equation}
\text{Cows}_{t,k+1} = (1-\text{animal_decay})*\text{Cows}_{t-1,k} \quad \forall (t,k) \in \text{Years} \setminus \{1\} \times \text{Ages} \setminus \{1,12\}
\end{equation}

- **Heifers Birth**: Heifers born in year $t$ depend on the number of dairy cows.

\begin{equation}
\text{Newborn}_t + \text{HF_sell}_t = \sum_{k \in \text{Ages} \setminus \{1,12\}}{\frac{\text{Birthrate}}{2}*\text{Cows}_{t,k}} \quad \forall t \in \text{Years}
\end{equation}

- **Final Dairy Cows**: The number of dairy cows at the end of the planning horizon must be within tolerances.

\begin{equation}
\text{min_final_animals} \leq \sum_{k \in \text{Ages} \setminus \{1,12\}}{\text{Cows}_{5,k}} \leq \text{max_final_animals}
\end{equation}

- **Initial Conditions**: Set the number of livestock available at the beginning of the planning horizon.

\begin{equation}
\text{Cows}_{1,1} = \text{initial_baby_animal_number}
\end{equation}

\begin{equation}
\text{Cows}_{1,2} = \text{initial_baby_animal_number}
\end{equation}

\begin{equation}
\text{Cows}_{1,k} = \text{initial_animals_number} \quad \forall k \in \text{Ages} \setminus \{1,2\}
\end{equation}

- **Yearly Profit**: Profit in year $t$ is driven by operations from crops and livestock, after accounting for labor, land and financial costs.

\begin{equation}
\text{Profit}_t = \frac{\text{BL_price}*\text{Birthrate}}{2}*\sum_{k \in \text{Ages} \setminus \{1,12\}}{\text{Cows}_{t,k}}
+ \text{baby_animal_price}*\text{HF_sell}_t
+ \text{animal_price}*\text{Cows}_{t,12}
\end{equation}

\begin{equation}
+ \text{animal_yearly_income}*\sum_{k \in \text{Ages} \setminus \{1,12\}}{\text{Cows}_{t,k}}
\end{equation}

\begin{equation}
+ \text{seed1_price}*\text{GR_sell}_t
+ \text{seed2_price}*\text{SB_sell}_t
\end{equation}

\begin{equation}
- \text{seed1_cost}*\text{GR_buy}_t
- \text{seed2_cost}*\text{SB_buy}_t
\end{equation}

\begin{equation}
- \text{Overtime_cost}*\text{Overtime}_t
- \text{Regular_time_cost}
\end{equation}

\begin{equation}
- \text{baby_animal_cost}*(\text{Newborn}_t + \text{Cows}_{t,1})
- \text{animal_cost}*\sum_{k \in \text{Ages} \setminus \{1,12\}}{\text{Cows}_{t,k}}
\end{equation}

\begin{equation}
- \text{seed1_land_cost}*\sum_{l \in \text{Lands}}{\frac{\text{GR}_{t,l}}{\text{seed1_yield}_l}}
- \text{seed2_land_cost}*\frac{\text{SB}_t}{\text{seed2_yield}} \\
- \text{Installment}*\sum_{d \in \text{Years}:d \leq t}{\text{Outlay}_d}
\quad \forall t \in \text{Years}
\end{equation}

---
## Python Implementation

We import the Gurobi Python Module and other Python libraries.

In [4]:
%pip install gurobipy

Note: you may need to restart the kernel to use updated packages.


In [5]:
import numpy as np
import pandas as pd

import gurobipy as gp
from gurobipy import GRB
from LayoutApp2 import inputs

# tested with Python 3.7.0 & Gurobi 9.0

## Input Data
We define all the input data of the model.

In [9]:
# Parameters

years = [1,2,3,4,5]
lands = [1,2,3,4]
ages = [1,2,3,4,5,6,7,8,9,10,11,12]
cow_ages = [2,3,4,5,6,7,8,9,10,11]

gr_area = {1: 20.0, 2: 30.0, 3: 20.0, 4: 10.0}
gr_yield = {1: 1.1,  2: 0.9, 3: 0.8, 4:0.65}
sb_yield = 1.5
housing_cap = 130
gr_intake = 0.6
sb_intake = 0.7
hf_land = 2/3.0
land_cap = 200
hf_labor = 10/100.0
cow_labor = 42/100.0
gr_labor = 4/100.0
sb_labor = 14/100.0
labor_cap = 5500/100.0
cow_decay = 0.02
hf_decay = 0.05
initial_hf = 9.5
initial_cows = 9.8
birthrate = 1.1
min_final_cows = 50
max_final_cows = 175
bl_price = 30
hf_price = 40
cow_price = 120
milk_price = 370
gr_price = 75
sb_price = 58
gr_cost = 90
sb_cost = 70
overtime_cost = 120
regular_time_cost = 4000
hf_cost = 50
cow_cost = 100
gr_land_cost = 15
sb_land_cost = 10
installment = 39.71

In [12]:
# Parameters

farming = {
    'animals': {
        'first_production_age': 2,
        'last_sell_age': 10,
        'min_final_animals': 50,
        'max_final_animals': 175,
        'animal_yearly_income': 370.0,
        'birthrate': 1.1,
    },
    'animals_needs': {
        'adult': {
            'land': 1.0,
            'labor': 0.42,
            'decay': 0.02,
            'initial_number': 9.8,
            'price': 120.0,
            'cost': 100.0,
        },
        'baby': {
            'land': 0.666,
            'labor': 0.1,
            'decay': 0.05,
            'initial_number': 9.5,
            'price': 40.0,
            'cost': 50.0,
        }
    },
    'capacity': {
        'housing': 130,
        'land': 200,
        'labor': 55,
    },
    'seeds':{
        'seed1': {
            'intake': 0.6,
            'labor': 0.04,
            'price': 75.0,
            'cost': 90.0,
            'land_cost': 15.0,
        },
        'seed2': {
            'yield': 1.5,
            'intake': 0.7,
            'labor': 0.14,
            'price': 58.0,
            'cost': 70.0,
            'land_cost': 10.0,
        }
    },
    'lands':{
        'area': {1: 20.0, 2: 30.0, 3: 20.0, 4: 10.0},
        'yield': {1: 1.1, 2: 0.9, 3: 0.8, 4: 0.65},
    },
    'years_number': 8,
    'overtime_cost': 1.20,
    'regular_time_cost': 4000.0,
    'installment': 39.71,
}

# Assigning values from dictionary to variables
animals = farming['animals']
animals_needs = farming['animals_needs']
capacity = farming['capacity']
seeds = farming['seeds']
lands = farming['lands']
years_number = farming['years_number']
overtime_cost = farming['overtime_cost']
regular_time_cost = farming['regular_time_cost']
installment = farming['installment']

# Printing the values to verify
print("animals:", animals)
print("animals_needs:", animals_needs)
print("capacity:", capacity)
print("seeds:", seeds)
print("lands:", lands)
print("years_number:", years_number)
print("overtime_cost:", overtime_cost)
print("regular_time_cost:", regular_time_cost)
print("installment:", installment)


#1. years = [1,2,3,4,5, 6, 7, 8]
years_number = farming['years_number'] # number of years given by the user
years = [i for i in range(1, years_number+1)] # plan years given by the user
print("years: ", years)

#2. lands = [1,2,3,4] 
lands_number = len(farming['lands']['area']) # number of land types given by the user
lands = [i for i in range(1, lands_number+1)] # land types given by the user
print("lands: ", lands)

#3. animals 
#animal_ages = [2,3,4,5,6,7,8,9,10,11] # animal ages (before having to sell them) given by the user: from ... to ...
#3.1 animals
#tableau1 : {
#              first_production_age    last_sell_age       min_final_animals       max_final_animals      animal_yearly_income       birthrate
#cow
animal_first_production_age = farming['animals']['first_production_age'] # first production age of the animal
animal_last_sell_age = farming['animals']['last_sell_age'] # last sell age of the animal
animal_ages = [i for i in range(animal_first_production_age, animal_last_sell_age+1)] # animal ages (before having to sell them) given by the user: from ... to ...
# ages = [1,2,3,4,5,6,7,8,9,10,11,12] # ages = animal_ages + [1] + ... + [min(animal_ages)-1] + [max(animal_ages)+1] 
ages = [i for i in range(1, max(animal_ages)+1)] 
# min_final_animals = 50
# max_final_animals = 175
min_final_animals = farming['animals']['min_final_animals'] # minimum number of final cows
max_final_animals = farming['animals']['max_final_animals'] # maximum number of final cows
#animal_yearly_income = 370 # yearly milk income
animal_yearly_income = farming['animals']['animal_yearly_income'] # yearly milk income
# birthrate = 1.1
birthrate = farming['animals']['birthrate'] # birthrate
#} fin de tableau 1



#tableau2 : {
#             land      labor    decay    initial_number     price    cost   
#cow    
#heifer

#cow land = 1
animal_land = farming['animals_needs']['adult']['land'] # land needed for a cow
# animal_labor = 42/100.0 # labor needed for a cow
animal_labor = farming['animals_needs']['adult']['labor'] # labor needed for a cow
#animal_decay = 0.02
animal_decay = farming['animals_needs']['adult']['decay'] # animal decay
# initial_animals_number = 9.8
initial_animals_number = farming['animals_needs']['adult']['initial_number'] # initial number of cows
#animal_price = 120
animal_price = farming['animals_needs']['adult']['price'] # cow price
#animal_cost = 100 #Yearly cost for supporting a cow.
animal_cost = farming['animals_needs']['adult']['cost'] #Yearly cost for supporting a cow.
print("animal_ages: ", animal_ages)
print("possible ages: ", ages)
print("animal_labor: ", animal_labor)
print("animal_decay: ", animal_decay)
print("initial_animals_number: ", initial_animals_number)
print("min_final_animals: ", min_final_animals)
print("max_final_animals: ", max_final_animals)
print("animal_price: ", animal_price)
print("animal_yearly_income: ", animal_yearly_income)
print("birthrate: ", birthrate)
print("animal_cost: ", animal_cost)


#3.2 heifers
# baby_animal_land = 2/3.0 # land needed for a heifer (heifer is a young cow that has not yet given birth to a calf)
baby_animal_land = farming['animals_needs']['baby']['land'] # land needed for a heifer
# baby_animal_labor = 10/100.0 # labor needed for a heifer
baby_animal_labor = farming['animals_needs']['baby']['labor'] # labor needed for a heifer
# baby_animal_decay = 0.05
baby_animal_decay = farming['animals_needs']['baby']['decay'] # heifer decay
# initial_baby_animal_number = 9.5
initial_baby_animal_number = farming['animals_needs']['baby']['initial_number'] # initial number of heifers
# baby_animal_price = 40 # heifers price (a heifer is a female young cow)
baby_animal_price = farming['animals_needs']['baby']['price'] # heifers price
# baby_animal_cost = 50 #Yearly cost for supporting a heifer.
baby_animal_cost = farming['animals_needs']['baby']['cost'] # Yearly cost for supporting a heifer.
print("baby_animal_land:", baby_animal_land)
print("baby_animal_labor:", baby_animal_labor)
print("baby_animal_decay:", baby_animal_decay)
print("initial_baby_animal_number:", initial_baby_animal_number)
print("baby_animal_price:", baby_animal_price)
print("baby_animal_cost:", baby_animal_cost) 
#} end of table 2


#4. housing_cap && land_cap && labor_cap
# tableau 3: capacity
#              housing         land            labor
#capacity
# housing_cap = 130
housing_cap = farming['capacity']['housing'] # housing capacity given by the user
# land_cap = 200 # land capacity which is the maximum land that can be used for farming (in acres)
land_cap = farming['capacity']['land'] # land capacity which is the maximum land that can be used for farming (in acres)
# labor_cap = 5500/100.0
labor_cap = farming['capacity']['labor'] # labor capacity which is the maximum labor that can be used for farming (in hours)
print("housing_cap: ", housing_cap)
print("land_cap: ", land_cap)
print("labor_cap: ", labor_cap)
#} fin de tableau 3


#5. seeds
#tableau4: {
#              seed1_area             seed1_yield
#land1
#...
#landn

#5.1. seed1 : grains
# lands_area = {1: 20.0, 2: 30.0, 3: 20.0, 4: 10.0} # area of land type i (in acres) given by the user
seed1_area = farming['lands']['area'] # area of land type i (in acres) given by the user

# seed1_yield_lands = {1:1.1, 2:0.9, 3:0.8, 4:0.65} 
seed1_yield = farming['lands']['yield'] # yield of seed1 in land type i (in tons per acre) given by the user

print("seed1_area: ", seed1_area)
print("seed1_yield: ", seed1_yield)
#} fin de tableau 4


#tableau 5:{
#             intake     labor    price    cost    land_cost
#gr
#sb

# seed1_intake = 0.6 # grains intake (intake means the amount of food that the animal eats)
seed1_intake = farming['seeds']['seed1']['intake'] # grains intake (intake means the amount of food that the animal eats)
# seed1_labor = 4/100.0
seed1_labor = farming['seeds']['seed1']['labor'] # labor needed for a grain
#seed1_price = 75 # Price for selling a ton of grain
seed1_price = farming['seeds']['seed1']['price'] # Price for selling a ton of grain
# seed1_cost = 90 # Cost for buying a ton of grain
seed1_cost = farming['seeds']['seed1']['cost'] # Cost for buying a ton of grain
# seed1_land_cost = 15 #Yearly cost for supporting an acre of land devoted to grain.
seed1_land_cost = farming['seeds']['seed1']['land_cost'] #Yearly cost for supporting an acre of land devoted to grain.
print("seed1_area: ", seed1_area)
print("seed1_yield: ", seed1_yield)
print("seed1_intake: ", seed1_intake)
print("seed1_labor: ", seed1_labor)
print("seed1_price: ", seed1_price)
print("seed1_cost: ", seed1_cost)
print("seed1_land_cost: ", seed1_land_cost)


#5.2. seed2 : soybeans
# seed2_yield = 1.5
seed2_yield = farming['seeds']['seed2']['yield'] # yield of seed2 in land type i (in tons per acre) given by the user
# seed2_intake = 0.7
seed2_intake = farming['seeds']['seed2']['intake'] # soybean intake (intake means the amount of food that the animal eats)
# seed2_labor = 14/100.0
seed2_labor = farming['seeds']['seed2']['labor'] # labor needed for a soybean
# seed2_price = 58 # Price for selling a ton of soybean
seed2_price = farming['seeds']['seed2']['price'] # Price for selling a ton of soybean
# seed2_cost = 70 # Cost for buying a ton of soybean
seed2_cost = farming['seeds']['seed2']['cost'] # Cost for buying a ton of soybean
# seed2_land_cost = 10 #Yearly cost for supporting an acre of land devoted to soybeans.
seed2_land_cost = farming['seeds']['seed2']['land_cost'] #Yearly cost for supporting an acre of land devoted to soybeans.
print("seed2_yield: ", seed2_yield)
print("seed2_intake: ", seed2_intake)
print("seed2_labor: ", seed2_labor)
print("seed2_price: ", seed2_price)
print("seed2_cost: ", seed2_cost)
print("seed2_land_cost: ", seed2_land_cost)
#} fin de tableau 5


#6. labor cost
#6.1. overtime_cost = 1,20 # Cost for getting an hour of overtime.
overtime_cost = farming['overtime_cost'] # Cost for getting an hour of overtime.
print("overtime_cost: ", overtime_cost)

#6.2. regular_time_cost = 4000 #Cost for having 5,500 hours of labor in regular time.
regular_time_cost = farming['regular_time_cost'] #Cost for having labor_cap hours of labor in regular time.
print("regular_time_cost: ", regular_time_cost)

#installment = 39.71 #Annual payment for each  $200  loan
installment = farming['installment'] #Annual payment for each  $200  loan
print("installment: ", installment)

animals: {'first_production_age': 2, 'last_sell_age': 10, 'min_final_animals': 50, 'max_final_animals': 175, 'animal_yearly_income': 370.0, 'birthrate': 1.1}
animals_needs: {'adult': {'land': 1.0, 'labor': 0.42, 'decay': 0.02, 'initial_number': 9.8, 'price': 120.0, 'cost': 100.0}, 'baby': {'land': 0.666, 'labor': 0.1, 'decay': 0.05, 'initial_number': 9.5, 'price': 40.0, 'cost': 50.0}}
capacity: {'housing': 130, 'land': 200, 'labor': 55}
seeds: {'seed1': {'intake': 0.6, 'labor': 0.04, 'price': 75.0, 'cost': 90.0, 'land_cost': 15.0}, 'seed2': {'yield': 1.5, 'intake': 0.7, 'labor': 0.14, 'price': 58.0, 'cost': 70.0, 'land_cost': 10.0}}
lands: {'area': {1: 20.0, 2: 30.0, 3: 20.0, 4: 10.0}, 'yield': {1: 1.1, 2: 0.9, 3: 0.8, 4: 0.65}}
years_number: 8
overtime_cost: 1.2
regular_time_cost: 4000.0
installment: 39.71
years:  [1, 2, 3, 4, 5, 6, 7, 8]
lands:  [1, 2, 3, 4]
animal_ages:  [2, 3, 4, 5, 6, 7, 8, 9, 10]
possible ages:  [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
animal_labor:  0.42
animal_decay:  0

In [13]:
# Parameters

farming {
    'animals': {
        'first_production_age' ,
        'last_sell_age' ,
        'min_final_animals' ,
        'max_final_animals' ,
        'animal_yearly_income' ,
        'birthrate': ,
    }
    'animals_needs': {
        'adult': {
            'land' ,
            'labor' ,
            'decay' ,
            'initial_number' ,
            'price' ,
            'cost' ,
        }
        'baby': {
            'land' ,
            'labor' ,
            'decay' ,
            'initial_number',
            'price',
            'cost' ,
        }
    }
    'capacity': {
        'housing' ,
        'land',
        'labor' ,
    }
    'seeds':{
        'seed1': {
            'intake' ,
            'labor' ,
            'price' ,
            'cost' ,
            'land_cost' ,
        }
        'seed2': {
            'labor',
            'price' ,
            'cost' ,
            'land_cost' ,
        }
    }
    'lands':{
        'area': {},
        'yield': {},
    }
    'years_number',
    'overtime_cost',
    'regular_time_cost',
    'installment',

}

#1. years = [1,2,3,4,5, 6, 7, 8]
years_number = int(input("Enter the number of years: ")) # number of years given by the user
years = [i for i in range(1, years_number+1)] # plan years given by the user
print("years: ", years)

#2. lands = [1,2,3,4] 
lands_number = int(input("Enter the number of land types: ")) # number of land types given by the user
lands = [i for i in range(1, lands_number+1)] # land types given by the user
print("lands: ", lands)

#3. animals 
#animal_ages = [2,3,4,5,6,7,8,9,10,11] # animal ages (before having to sell them) given by the user: from ... to ...
#3.1 animals
#tableau1 : {
#              first_production_age    last_sell_age       min_final_animals       max_final_animals      animal_yearly_income       birthrate
#cow
animal_first_production_age = int(input("Enter the first production age of the animal: ")) # 
animal_last_sell_age = int(input("Enter the last sell age of the animal: ")) #
animal_ages = [i for i in range(animal_first_production_age, animal_last_sell_age+1)] # animal ages (before having to sell them) given by the user: from ... to ...
# ages = [1,2,3,4,5,6,7,8,9,10,11,12] # ages = animal_ages + [1] + ... + [min(animal_ages)-1] + [max(animal_ages)+1] 
ages = [i for i in range(1, max(animal_ages)+1)] 
# min_final_animals = 50
# max_final_animals = 175
min_final_animals = int(input("Enter the minimum number of final cows: ")) # minimum number of final cows
max_final_animals = int(input("Enter the maximum number of final cows: ")) # maximum number of final cows
#animal_yearly_income = 370 # yearly milk income
animal_yearly_income = float(input("Enter the yearly milk income: ")) # yearly milk income
# birthrate = 1.1
birthrate = float(input("Enter the birthrate: ")) # birthrate
#} fin de tableau 1



#tableau2 : {
#             land      labor    decay    initial_number     price    cost   
#cow    
#heifer

#cow land = 1
animal_land = float(input("Enter the land needed for a cow: ")) # land needed for a cow
# animal_labor = 42/100.0 # labor needed for a cow
animal_labor = float(input("Enter the labor needed for a cow: ") ) # labor needed for a cow
#animal_decay = 0.02
animal_decay = float(input("Enter the cow decay: ")) # cow decay
# initial_animals_number = 9.8
initial_animals_number = float(input("Enter the initial number of cows: ")) # initial number of cows
#animal_price = 120
animal_price = float(input("Enter the cows price: ")) # cows price
#animal_cost = 100 #Yearly cost for supporting a cow.
animal_cost = float(input("Enter the yearly cost for supporting a cow: ")) #Yearly cost for supporting a cow.
print("animal_ages: ", animal_ages)
print("possible ages: ", ages)
print("animal_labor: ", animal_labor)
print("animal_decay: ", animal_decay)
print("initial_animals_number: ", initial_animals_number)
print("min_final_animals: ", min_final_animals)
print("max_final_animals: ", max_final_animals)
print("animal_price: ", animal_price)
print("animal_yearly_income: ", animal_yearly_income)
print("birthrate: ", birthrate)
print("animal_cost: ", animal_cost)



#3.2 heirfers
# baby_animal_land = 2/3.0 # land needed for a heirfer (heirfer is a young cow that has not yet given birth to a calf)
baby_animal_land = float(input("Enter the land needed for a heirfer: ")) # land needed for a heirfer (heirfer is a young cow that has not yet given birth to a calf)
# baby_animal_labor = 10/100.0 # labor needed for a heirfer
baby_animal_labor = float(input("Enter the labor needed for a heirfer: ")) # labor needed for a heirfer
#baby_animal_decay = 0.05
baby_animal_decay = float(input("Enter the heirfer decay: ")) # heirfer decay
# initial_baby_animal_number = 9.5
initial_baby_animal_number = float(input("Enter the initial number of heirfers: ")) # initial number of heirfers
#bl_price = 30 # bullocks price (a bullock is a male young cow)
#baby_animal_price = 40 # heirfers price (a heirfer is a female young cow)
baby_animal_price = float(input("Enter the heirfers price: ")) # heirfers price
#baby_animal_cost = 50 #Yearly cost for supporting a heifer.
baby_animal_cost = float(input("Enter the yearly cost for supporting a heifer: ")) #Yearly cost for supporting a heifer.
print("baby_animal_land:", baby_animal_land)
print("baby_animal_labor:", baby_animal_labor)
print("baby_animal_decay:", baby_animal_decay)
print("initial_baby_animal_number:", initial_baby_animal_number)
print("baby_animal_price:", baby_animal_price)
print("baby_animal_cost:", baby_animal_cost) 
#} fin de tableau 2


#4. housing_cap && land_cap && labor_cap
# tableau 3: capacity
#              housing         land            labor
#capacity
#housing_cap = 130
housing_cap = int(input("Enter the housing capacity: ")) # housing capacity given by the user
# land_cap = 200 # land capacity which is the maximum land that can be used for farming (in acres)
land_cap = int(input("Enter the land capacity: ")) # land capacity which is the maximum land that can be used for farming (in acres)
# labor_cap = 5500/100.0
labor_cap = int(input("Enter the labor capacity: ")) # labor capacity which is the maximum labor that can be used for farming (in hours)
print("housing_cap: ", housing_cap)
print("land_cap: ", land_cap)
print("labor_cap: ", labor_cap)
#} fin de tableau 3


#5. seeds
#tableau4: {
#              seed1_area             seed1_yield
#land1
#...
#landn

#5.1. seed1 : grains
# lands_area = {1: 20.0, 2: 30.0, 3: 20.0, 4: 10.0} # area of land type i (in acres) given by the user
seed1_area = {} # area of land type i (in acres) given by the user
for i in range(1, lands_number+1):
    seed1_area[i] = float(input("Enter the area of land type " + str(i) + ": ")) 

# seed1_yield_lands = {1:1.1, 2:0.9, 3:0.8, 4:0.65} 
seed1_yield = {}
for i in range(1, lands_number+1):
    seed1_yield[i] = float(input("Enter the yield of grain in land type " + str(i) + ": "))
#} fin de tableau 4

#tableau 5:{
#             intake     labor    price    cost    land_cost
#gr
#sb

# seed1_intake = 0.6 # grains intake (intake means the amount of food that the animal eats)
seed1_intake = float(input("Enter the grains intake: ")) # grains intake (intake means the amount of food that the animal eats)
# seed1_labor = 4/100.0
seed1_labor = float(input("Enter the labor needed for a grain: ")) # labor needed for a grain
#seed1_price = 75 # Price for selling a ton of grain
seed1_price = float(input("Enter the price for selling a ton of grain: ")) # Price for selling a ton of grain
# seed1_cost = 90 # Cost for buying a ton of grain
seed1_cost = float(input("Enter the cost for buying a ton of grain: ")) # Cost for buying a ton of grain
# seed1_land_cost = 15 #Yearly cost for supporting an acre of land devoted to grain.
seed1_land_cost = float(input("Enter the yearly cost for supporting an acre of land devoted to grain: ")) #Yearly cost for supporting an acre of land devoted to grain.
print("seed1_area: ", seed1_area)
print("seed1_yield: ", seed1_yield)
print("seed1_intake: ", seed1_intake)
print("seed1_labor: ", seed1_labor)
print("seed1_price: ", seed1_price)
print("seed1_cost: ", seed1_cost)
print("seed1_land_cost: ", seed1_land_cost)


#5.2. seed2 : soybeans
# seed2_yield = 1.5 
seed2_yield = float(input("Enter the yield of soybean: ")) # yield of soybean
# seed2_intake = 0.7
seed2_intake = float(input("Enter the soybean intake: ")) # soybean intake (intake means the amount of food that the animal eats)
# seed2_labor = 14/100.0
seed2_labor = float(input("Enter the labor needed for a soybean: ")) # labor needed for a soybean
# seed2_price = 58 # Price for selling a ton of soybean
seed2_price = float(input("Enter the price for selling a ton of soybean: ")) # Price for selling a ton of soybean
# seed2_cost = 70 # Cost for buying a ton of soybean
seed2_cost = float(input("Enter the cost for buying a ton of soybean: ")) # Cost for buying a ton of soybean
# seed2_land_cost = 10 #Yearly cost for supporting an acre of land devoted to soybeans.
seed2_land_cost = float(input("Enter the yearly cost for supporting an acre of land devoted to soybeans: ")) #Yearly cost for supporting an acre of land devoted to soybeans.
print("seed2_yield: ", seed2_yield)
print("seed2_intake: ", seed2_intake)
print("seed2_labor: ", seed2_labor)
print("seed2_price: ", seed2_price)
print("seed2_cost: ", seed2_cost)
print("seed2_land_cost: ", seed2_land_cost)
#} fin de tableau 5


#6. labor cost
#6.1. overtime_cost = 1,20 # Cost for getting an hour of overtime.
overtime_cost = float(input("Enter the cost for getting an hour of overtime: ")) # Cost for getting an hour of overtime.
print("overtime_cost: ", overtime_cost)

#6.2. regular_time_cost = 4000 #Cost for having 5,500 hours of labor in regular time.
regular_time_cost = float(input("Enter the cost for having" + labor_cap + "hours of labor in regular time: ")) #Cost for having labor_cap hours of labor in regular time.
print("regular_time_cost: ", regular_time_cost)

#installment = 39.71 #Annual payment for each  $200  loan
installment = float(input("Enter the annual payment for each $200 loan: ")) #Annual payment for each  $200  loan
print("installment: ", installment)

SyntaxError: invalid syntax (3703465092.py, line 3)

{1: 20.0, 2: 30.0, 3: 10.0, 4: 20.0}


{1: 1.1, 2: 0.9, 3: 0.8, 4: 0.7}


## Model Deployment

We create a model and the variables. For each, year we have continuous variables, which tell us how much sugar beet is grown (in tons), how much grain is bought (in tons), how much grain is sold (in tons), how much sugar beet is bought (in tons), how much sugar beet is sold (in tons), how much extra labor is recruited, how much capital outlay there is, how many heifers are sold at birth, how much profit there is, and how many cows are newborns (age 0).

For each year and each land group, there is a continuous variable, which tells us how much grain is grown on that land group. For each year and each cow age, there is a continuous variable that tells us how many cows exists in the current year of that age.

In [14]:
model = gp.Model('Farming')
sb = model.addVars(years, vtype=GRB.CONTINUOUS, name="SB")
gr_buy = model.addVars(years, vtype=GRB.CONTINUOUS, name="GR_buy")
gr_sell = model.addVars(years, vtype=GRB.CONTINUOUS, name="GR_sell")
sb_buy = model.addVars(years, vtype=GRB.CONTINUOUS, name="SB_buy")
sb_sell = model.addVars(years, vtype=GRB.CONTINUOUS, name="SB_sell")
overtime = model.addVars(years, vtype=GRB.CONTINUOUS, name="Overtime")
outlay = model.addVars(years, vtype=GRB.CONTINUOUS, name="Outlay")
hf_sell = model.addVars(years, vtype=GRB.CONTINUOUS, name="HF_sell")
newborn = model.addVars(years, vtype=GRB.CONTINUOUS, name="Newborn")
profit = model.addVars(years, vtype=GRB.CONTINUOUS, name="Profit")
gr = model.addVars(years, lands, vtype=GRB.CONTINUOUS, name="GR")
cows = model.addVars(years, ages, vtype=GRB.CONTINUOUS, name="Cows")

Next we insert the constraints:

There is only a housing capacity for 130 cows per year. It is possible that there are more than 130 cows, but housing these additional cows will require additional costs related to renting houses, which is covered with the `Outlay` variables.

In [15]:
# 1. Housing capacity

HousingCap = model.addConstrs((newborn[year] +
                    cows[year,1] +
                    gp.quicksum(cows[year,age] for age in animal_ages) -
                    gp.quicksum(outlay[d] for d in years if d <= year)
                    <= housing_cap for year in years), name="Housing_cap")

After selling, buying, and producing grains and sugar beet, there needs to be enough of them in storage to feed all the cows.

In [16]:
# 2.1 Food consumption (Grain)

GrainConsumption = model.addConstrs((gp.quicksum(seed1_intake*cows[year, age] for age in animal_ages)
                  <= gr_buy[year] - gr_sell[year] + gr.sum(year, '*')
                  for year in years), name="Grain_consumption")

# 2.1 Food consumption (Sugar beet)
SugarbeetConsumption = model.addConstrs((gp.quicksum(seed2_intake*cows[year, age] for age in animal_ages)
                  <= sb_buy[year] - sb_sell[year] + sb[year]
                  for year in years), name="Sugar_beet_consumption")

The grain produced on a land group cannot exceed the specified production capacity of that land group.

In [17]:
# 3. Grain growing

GrainGrowing = model.addConstrs((gr[year, land] <= seed1_yield[land]*seed1_area[land]
                  for year in years for land in lands), name="Grain_growing")

Each cow needs a certain number of acres to support it. The amount depends on the age of the cow. There are 200 acres available at most.

In [30]:
# 4. Land capacity

LandCap = model.addConstrs((sb[year]/seed2_yield + baby_animal_land*(newborn[year] + cows[year,i] for i in range(1, cow_first_production_age))
                  + gp.quicksum((1/seed1_yield[land])*gr[year, land] for land in lands)
                  + gp.quicksum(animal_land*cows[year, age] for age in animal_ages)
                  <= land_cap for year in years), name="Land_capacity")

TypeError: unsupported operand type(s) for *: 'float' and 'generator'

Each cow and each acre requires a certain amount of worker time to maintain. The farm is currently able to provide a fixed number of worker hours in a year. Any additional work that needs to be done requires external workers, for which there will be an additional cost.

In [20]:
# 5. Labor

Labor = model.addConstrs((baby_animal_labor*(newborn[year] + cows[year,1])
                  + gp.quicksum(animal_labor*cows[year, age] for age in animal_ages)
                  + gp.quicksum(seed1_labor/seed1_yield[land]*gr[year,land] for land in lands)
                  + seed2_labor/seed2_yield*sb[year] 
                  <= labor_cap + overtime[year] for year in years), name="Labor")

Each year a certain percentage of the cows die, depending on their age.

In [21]:
# 6.1 Continuity

Continuity1 = model.addConstrs((cows[year,1] == (1-baby_animal_decay)*newborn[year-1] 
                  for year in years if year > min(years)),
                 name="Continuity_a")

# 6.2 Continuity

Continuity2 = model.addConstrs((cows[year,2] == (1-baby_animal_decay)*cows[year-1,1] 
                  for year in years if year > min(years)),
                 name="Continuity_b")

# 6.3 Continuity

Continuity3 = model.addConstrs((cows[year,age+1] == (1-animal_decay)*cows[year-1,age]
                  for year in years for age in animal_ages if year > min(years) and age < max(animal_ages)),
                 name="Continuity_c")

Keep track of the number of cows; cows can come into/out of the model by being bought or sold or through birth.

In [22]:
# 7. Heifers birth

HeifersBirth = model.addConstrs((newborn[year] + hf_sell[year] 
                  == gp.quicksum(birthrate/2*cows[year,age] for age in animal_ages) for year in years)
                 , name="Heifers_birth")

At the end of the five years, the farmer wants at least 50 and at most 175 diary cows.

In [23]:
# 8. Final dairy cows
FinalDairyCows = model.addRange(gp.quicksum(cows[max(years), age] for age in animal_ages), min_final_animals, max_final_animals, name="Final_dairy_cows" )

In the first year, there are 9.5 one-year-old cows and 9.5 two-year-old cows. In addition, there are 9.8 cows for each age from three to 12. Note that we are solving this as an LP model to make it easier to solve. This can lead to fractional values for variables, which are in reality integers. 

In [24]:
# 9.1-9.2 Initial conditions

InitialHeifers = model.addConstrs((initial_baby_animal_number == cows[1, age] for age in ages if age < 3),
                 name="Initial_conditions")

# 9.3 Initial conditions

InitialCows = model.addConstrs((initial_animals_number == cows[1, age] for age in ages if age >= 3),
                 name="Initial_condition_cows")

The following constraints determine yearly profits. The costs for labor currently total $\$4,000$. The profit is influenced by the selling of bullocks and heifers, selling of 12-year-old-cows, selling of milk, selling of grain, selling of sugar beet, buying of grain, buying of sugar beet, labor costs, heifer costs, dairy cow costs, grain costs, sugar beet costs, and capital costs.

In [25]:
# 10. Yearly profit

YearlyProfit = model.addConstrs((profit[year]
                  == baby_animal_price*birthrate/2*gp.quicksum(cows[year, age] for age in animal_ages)
                  + baby_animal_price*hf_sell[year] + animal_price*cows[year, animal_last_sell_age]
                  + animal_yearly_income*gp.quicksum(cows[year, age] for age in animal_ages)
                  + seed1_price*gr_sell[year] + seed2_price*sb_sell[year]
                  - seed1_cost*gr_buy[year] - seed2_cost*sb_buy[year]
                  - overtime_cost*overtime[year] - regular_time_cost
                  - baby_animal_cost*(newborn[year] + cows[year,1])
                  - animal_cost*gp.quicksum(cows[year, age] for age in animal_ages)
                  - seed1_land_cost*gp.quicksum(gr[year, land]/seed1_yield[land] for land in lands)
                  - seed2_land_cost*sb[year]/seed2_yield
                  - installment*gp.quicksum(outlay[d] for d in years if d <= year)
                  for year in years), name="Yearly_profit")

The total profit of the planning horizon consists of the calculated profits minus the loan payments that remain pending:

In [26]:
# 0. Total profit

model.setObjective(gp.quicksum(profit[year] - installment*(year+4)*outlay[year] for year in years), GRB.MAXIMIZE)

Next, we start the optimization and Gurobi finds the optimal solution.

In [27]:
model.optimize()

Gurobi Optimizer version 11.0.1 build v11.0.1rc0 (win64 - Windows 10.0 (19045.2))

CPU model: Intel(R) Core(TM) i5-10300H CPU @ 2.50GHz, instruction set [SSE2|AVX|AVX2]
Thread count: 4 physical cores, 8 logical processors, using up to 8 threads

Optimize a model with 161 rows, 193 columns and 976 nonzeros
Model fingerprint: 0xe31f7712
Coefficient statistics:
  Matrix range     [4e-02, 4e+02]
  Objective range  [1e+00, 5e+02]
  Bounds range     [1e+02, 1e+02]
  RHS range        [7e+00, 4e+03]
Presolve removed 116 rows and 86 columns
Presolve time: 0.01s
Presolved: 45 rows, 107 columns, 450 nonzeros

Iteration    Objective       Primal Inf.    Dual Inf.      Time
       0    8.9600000e+32   8.000000e+30   8.960000e+02      0s

Solved in 46 iterations and 0.01 seconds (0.00 work units)
Infeasible or unbounded model


---
## Analysis

The optimal plan results in a total profit of $\$121,719.17$ over the five-year period the model covers. The detailed plan for each year is as follows.

### Financial Plan

This plan determines the profit and outlay at each period of the planning horizon. For example, the profit in year 1 is $\$21,906.1$ and the outlay is zero dollars.

In [28]:
rows = ["Profit", "Outlay"]
columns = years.copy()
finance_plan = pd.DataFrame(columns=columns, index=rows, data=0.0)

for year in years:
    if (abs(profit[year].x) > 1e-6):
        finance_plan.loc["Profit", year] = np.round(profit[year].x, 1)
    if (abs(outlay[year].x) > 1e-6):
        finance_plan.loc["Outlay", year] = np.round(outlay[year].x, 1)
finance_plan

AttributeError: Unable to retrieve attribute 'x'

### Plan for Grains
This plan defines the number of tons of grain to grow for each type of land group (rows) at each year of the planning horizon (columns). It also defines the number of tons of grain to buy and sell at each year of the planning horizon. For example, we are going to grow 22 tons of grain at land group 1 during year 2 . In addition, we are going to buy 35.1 tons of grain during year 2.

In [22]:
rows = lands.copy() + ["Buy", "Sell"]
columns = years.copy()
gr_plan = pd.DataFrame(columns=columns, index=rows, data=0.0)

for year, land in gr.keys():
    if (abs(gr[year, land].x) > 1e-6):
        gr_plan.loc[land, year] = np.round(gr[year, land].x, 1)
for year in years:
    if (abs(gr_buy[year].x) > 1e-6):
        gr_plan.loc["Buy", year] = np.round(gr_buy[year].x, 1)
    if (abs(gr_sell[year].x) > 1e-6):
        gr_plan.loc["Sell", year] = np.round(gr_sell[year].x, 1)
gr_plan

1     2     3     4     5
1     22.0  22.0  22.0  22.0  22.0
2      0.0   0.0   2.2   0.0   0.0
3      0.0   0.0   0.0   0.0   0.0
4      0.0   0.0   0.0   0.0   0.0
Buy   46.4  44.6  48.9  43.2  35.6
Sell   0.0   0.0   0.0   0.0   0.0

### Plan for Sugar Beet
This plan defines the number of tons of sugar beet to grow at each year of the planning horizon (columns). It also defines the number of tons of sugar beet to buy and sell at each year of the planning horizon. For example, we are going to grow 94 tons of sugar beet during year 2 . In addition, we are going to sell 27.4 tons of sugar beet during year 2.

In [23]:
rows = ["Grow", "Buy", "Sell"]
columns = years.copy()
sb_plan = pd.DataFrame(columns=columns, index=rows, data=0.0)

for year in years:
    if (abs(sb[year].x) > 1e-6):
        sb_plan.loc["Grow", year] = np.round(sb[year].x, 1)
    if (abs(sb_buy[year].x) > 1e-6):
        sb_plan.loc["Buy", year] = np.round(sb_buy[year].x, 1)
    if (abs(sb_sell[year].x) > 1e-6):
        sb_plan.loc["Sell", year] = np.round(sb_sell[year].x, 1)
sb_plan

1      2      3      4      5
Grow  91.5  105.8  109.8  130.3  146.7
Buy    0.0    0.0    0.0    0.0    0.0
Sell  13.3   29.7   26.2   55.8   80.9

### Plan for Heifers

This plan shows number of heifers to sell and raise at each period of the planning horizon. For example, we are going to sell 40.8 heifers and raise 11.6 heifers during year 2.

In [24]:
rows = ["Sell", "Raise"]
columns = years.copy()
livestock_plan = pd.DataFrame(columns=columns, index=rows, data=0.0)

for year in years:
    if (abs(hf_sell[year].x) > 1e-6):
        livestock_plan.loc["Sell", year] = np.round(hf_sell[year].x, 1)
    if (abs(newborn[year].x) > 1e-6):
        livestock_plan.loc["Raise", year] = np.round(newborn[year].x, 1)
livestock_plan

1     2     3     4     5
Sell   30.9  52.3  57.4  51.2  45.2
Raise  22.8   0.0   0.0   0.0   0.0

---
## References

H. Paul Williams, Model Building in Mathematical Programming, fifth edition.

Copyright © 2020 Gurobi Optimization, LLC